### PR TITLE
oneplus2: Import from OnePlus2Oxygen_14_OTA_030_all_1704191749

### PR DESCRIPTION
**Pull request by aviraxp**
* Fix network drops (ril libs)
* Update camera libs
* Update location libs
* Update slim_daemon binaries

### CODE REVIEW

**Comment by aviraxp** [comment]
@Grarak @OzzysCmAcc Could you please review this?

From my test it works.

I leave out some kanged libs, and the OOS3.5.9 source is here: https://www.androidfilehost.com/?fid=889764386195913566

**Comment by OzzysCmAcc** [comment]
have you tested that network drops have really gone?

**Comment by aviraxp** [comment]
I had network drops (rild crash because segfault caused by ril lib) when using tencent contacts app, with the new libs it is gone. But I strongly advice to make a test build before merge it, or you or Grarak re-do this import.

**Comment by aviraxp** [comment]
The location blobs have issues. I guess we should not ship this but keep hex-edited blobs by Grarak.

```
07-06 23:42:22.083 14222 14222 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
07-06 23:42:22.083 14222 14222 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8loc_core10LocApiBase8reportSvER12GnssSvStatusR19GpsLocationExtendedPv" referenced by "/system/lib64/libloc_api_v02.so"...
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1562)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at com.qualcomm.location.izatserviceprovider.service.IzatServiceBase.<clinit>(IzatServiceBase.java:202)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3198)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:383)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:237)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-06 23:42:22.083 14222 14222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-06 23:42:22.098 14222 14222 W DropBoxManagerService: Dropping: system_server_crash (1187 > 0 bytes)
```

**Comment by aviraxp** [comment]
Close this. Need more test.

**Pull request closed without merging**
